### ISSUE TITLE
Certificate verify failed (unable to get local issuer certificate) 

### ISSUE THREAD

**Issue by shresthaujjwal** [github-changelog-generator/docker-github-changelog-generator#29]
Getting SSL Cert Error with 1.15.0 Docker Image
ferrarimarco/github-changelog-generator:latest
Version: 1.15.0
```
Fetching tags...
[1mTraceback[m (most recent call last):
	43: from /usr/local/bundle/bin/github_changelog_generator:23:in `<main>'
	42: from /usr/local/bundle/bin/github_changelog_generator:23:in `load'
	41: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/bin/github_changelog_generator:5:in `<top (required)>'
	40: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator.rb:35:in `run'
	39: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/generator/generator.rb:46:in `compound_changelog'
	38: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/generator/generator_tags.rb:10:in `fetch_and_filter_tags'
	37: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:85:in `get_all_tags'
	36: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'
	35: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	34: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	33: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	32: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'
	31: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:85:in `block in get_all_tags'
	30: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:112:in `github_fetch_tags'
	29: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:93:in `calculate_pages'
	28: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'
	27: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	26: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	25: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	24: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'
	23: from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:94:in `block in calculate_pages'
	22: from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/client/repositories.rb:528:in `tags'
	21: from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/connection.rb:84:in `paginate'
	20: from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/connection.rb:156:in `request'
	19: from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	18: from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/connection.rb:138:in `get'
	17: from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/connection.rb:387:in `run_request'
	16: from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:143:in `build_response'
	15: from /usr/local/bundle/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
	14: from /usr/local/bundle/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
	13: from /usr/local/bundle/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
	12: from /usr/local/bundle/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
	11: from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/response.rb:8:in `call'
	10: from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:38:in `call'
	 9: from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
	 8: from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:43:in `block in call'
	 7: from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:85:in `perform_request'
	 6: from /usr/local/lib/ruby/2.6.0/net/http.rb:1228:in `get'
	 5: from /usr/local/lib/ruby/2.6.0/net/http.rb:1470:in `request'
	 4: from /usr/local/lib/ruby/2.6.0/net/http.rb:919:in `start'
	 3: from /usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	 2: from /usr/local/lib/ruby/2.6.0/net/http.rb:996:in `connect'
	 1: from /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': [1mSSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) ([1;4mOpenSSL::SSL::SSLError[m[1m)[m
```

**Comment by ferrarimarco** [comment]
Should be solved in the latest release
